// <auto-generated />
using E_Commerce.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce.Migrations
{
    [DbContext(typeof(MyContex))]
    [Migration("20241101115213_admin migration")]
    partial class adminmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_Commerce.Models.Admin", b =>
                {
                    b.Property<int>("Admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admin_id"), 1L, 1);

                    b.Property<int>("Admin_Email")
                        .HasColumnType("int");

                    b.Property<int>("Admin_image")
                        .HasColumnType("int");

                    b.Property<string>("Admin_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Admin_password")
                        .HasColumnType("int");

                    b.HasKey("Admin_id");

                    b.ToTable("tbl_admin");
                });
#pragma warning restore 612, 618
        }
    }
}
